package pegasus;

public enum PegasusCounter {
    NUMBER_SELF_LOOP,
    NUMBER_BLOCK_VECTOR,
    NUMBER_BLOCK_MATRIX,
    NUMBER_FINAL_VECTOR,
    NUMBER_INCOMPLETE_VECTOR,
    ERROR_MISSING_SELF_VECTOR,
    ERROR_NO_INITIAL_VECTOR
}
